### ISSUE TITLE
fails to build on Python 3.11 due to a bug in cchardet

### ISSUE THREAD

**Issue by salfter** [gutenbergtools/ebookmaker#236]
I tried installing this with ```pipenv install ebookmaker```, but got an error while building cchardet:

```
[pipenv.exceptions.InstallError]:       src/cchardet/_cchardet.cpp:196:12: fatal error: longintrepr.h: No such file or directory
[pipenv.exceptions.InstallError]:         196 |   #include "longintrepr.h"
[pipenv.exceptions.InstallError]:             |            ^~~~~~~~~~~~~~~
[pipenv.exceptions.InstallError]:       compilation terminated.
[pipenv.exceptions.InstallError]:       error: command '/usr/bin/g++' failed with exit code 1
[pipenv.exceptions.InstallError]:       [end of output]
```

This is most likely related to https://github.com/PyYoshi/cChardet/issues/81.  I was able to get a working ebookmaker with ```
pipenv install cchardet==2.2.0a2 && pipenv install ebookmaker```.

**Comment by eshellman** [comment]
duplicate of #211  
will add your solution to the next release
